version: '3'

services:
  frontend:
    build: ./packages/frontend
    ports:
      - "5173:3000"

  backend:
    build: ./packages/backend
    ports:
      - "8000:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: e-commerce-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
